name = "yafff"
version = "1.0.0"


target = "javascript"


[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
esgleam = ">= 0.8.0 and < 1.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
